name: streamlit_env
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pyodbc
  - pip
  - pip:
      - streamlit
      - streamlit_extras
      - plotly
      - altair
      - matplotlib
      - requests
      - toml
